### ISSUE TITLE
TODO implement useExistingConfig()

### ISSUE THREAD

**Issue by lionelkouame** [lionelkouame/wordpress-cli#3]
- [x] add file project name "projects.xml"

- [x] Read file project xml

- [x] display list project

- [ ] Ask choice of project

- [ ] Get choice of project
